version: '3.7'
services:

    redis:
        image: docker.io/library/redis:6.0.6
        container_name: redis
        hostname: 'redis'
        restart: always
        environment:
        - TZ=Europe/Zurich
        command: redis-server --requirepass 123456
        ports:
        - "3000:6379"
        volumes:
        - ./conf/redis.conf:/usr/local/etc/redis/config/redis.conf:ro


    fplserver:
        build: .
        ports:
            - "6669:8080/udp"
            - "4201:8081"